### ISSUE TITLE
Pilot Mode - Autogen Data for Playbooks

### ISSUE THREAD

**Issue by Solarswordsman** [Solarswordsman/BeamSaber#3]
All the auto generated data for the various playbooks (special abilities, friends, xp triggers, gather information methods, playbook specific items and vehicle items) needs to be completed.

(Ace is mostly complete as an example of the structure)

**Comment by flyinggrizzly** [comment]
I'm happy to do this over the next week/end. Playbooks that need to be added:

- [x] (finish) Ace (#5)
- [x] Bureaucrat (#12)
- [x] Empath (#11)
- [x] Envoy (50e872e)
- [x] Hacker (15788a2..cd30385)
- [x] Infiltrator (014d6d1)
- [x] Officer (7c44e59)
- [x] Scout (d9389c0)
- [x] Soldier (deb796d)
- [x] Technician (#6)

**Comment by Solarswordsman** [comment]
All Pilot autogen data for Beam Saber V0.411 is entered!
